### ISSUE TITLE
Странные вещи со счетчиком непрочитанных сообщений

### ISSUE THREAD

**Issue by kesha1225** [catofsof/astrak#4]
Странные вещи со счетчиком непрочитанных сообщений

![изображение](https://user-images.githubusercontent.com/48860626/74612672-9b9c5400-5118-11ea-91eb-4d915c211d24.png)
![изображение](https://user-images.githubusercontent.com/48860626/74612677-9f2fdb00-5118-11ea-848d-1a20035894e8.png)

**Comment by catofsof** [comment]
Исправлено. Обновление клиента не требуется.
