### ISSUE TITLE
Долгий ответ на /messages/dialogs

### ISSUE THREAD

**Issue by kesha1225** [catofsof/astrak#5]
Имея три диалога, ответ приходит в среднем за 0.9 сек

**Comment by catofsof** [comment]
Немного оптимизировал код. Ожидание ответа на локальной машине сократилось с 500 до 300 мс. Думаю, не сильный прирост производительности. Постараюсь сделать быстрее но немного позже. Спасибо.

**Comment by catofsof** [comment]
Оптимизировано и находится в стадии тестирования.
