### ISSUE TITLE
Баг с загрузкой темы

### ISSUE THREAD

**Issue by Seder3214** [catofsof/astrak#9]
Баг с темой при первом запуске приложения.
![Screenshot_20200221-124237](https://user-images.githubusercontent.com/50592797/75023291-9b011600-54a8-11ea-9ac5-db1d5a8381b9.png)
![Screenshot_20200221-124230](https://user-images.githubusercontent.com/50592797/75023314-a48a7e00-54a8-11ea-8d99-c631d62dc640.png)
![Screenshot_20200221-124226](https://user-images.githubusercontent.com/50592797/75023316-a5231480-54a8-11ea-8997-bd20f642fe22.png)

**Comment by crinny** [comment]
привет даун ебаный сука

**Comment by catofsof** [comment]
Будет исправлено в следующем билде.
